---

version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    # secrets:
    #   - postgres_db
    #   - postgres_password
    #   - postgres_user

  app:
    image: nextcloud
    restart: always
    ports:
      - 8081:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud
      - NEXTCLOUD_ADMIN_USER=nextcloud
    depends_on:
      - db
    # secrets:
    #   - nextcloud_admin_password
    #   - nextcloud_admin_user
    #   - postgres_db
    #   - postgres_password
    #   - postgres_user

volumes:
  db:
  nextcloud: