---

# Source: https://dev.to/kuwv/why-i-use-ansible-over-docker-compose-edg

- name: Run Nextcloud
  hosts: localhost

  tasks:

    - name: Setup network for Nextcloud
      community.docker.docker_network:
        name: nextcloud-net
        state: "{{ sso_network_state | default('present') }}"

    - name: Setup volume for Postgres
      community.docker.docker_volume:
        name: postgres-data
        state: "{{ sso_volume_state | default('present') }}"

    - name: Setup volume for Nextcloud
      community.docker.docker_volume:
        name: nextcloud-data
        state: "{{ sso_volume_state | default('present') }}"

    - name: Check if Nextcloud DB is running
      community.docker.docker_container_info:
        name: nextcloud-db
      register: nextcloud_db_state

    - block:
        - name: Start Nextcloud DB
          community.docker.docker_container:
            name: nextcloud-db
            image: postgres
            volumes:
              - postgres-data:/var/lib/postresql/data
            networks_cli_compatible: true
            networks:
              - name: nextcloud-net
            ports:
              - "5432:5432"
            env:
              POSTGRES_DB: nextcloud
              POSTGRES_USER: nextcloud
              POSTGRES_PASSWORD: nextcloud
          register: nextcloud_db_register

        - name: nextcloud_db_register
          ansible.builtin.debug:
            var: nextcloud_db_register

        - name: Wait for nextcloud DB to accept connections
          ansible.builtin.wait_for:
            # host: "{{ nextcloud_db_register['container']\
            #   ['NetworkSettings']\
            #   ['Networks']\
            #   ['nextcloud-net']\
            #   ['IPAddress'] }}"
            host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
            port: 5432
            state: started
            connect_timeout: 1
            timeout: 30
          register: nextcloud_db_running
          until: nextcloud_db_running is success
          retries: 10
      when: not nextcloud_db_state.exists

    - name: Check if Nextcloud is running
      community.docker.docker_container_info:
        name: nextcloud
      register: nextcloud_state

    - block:
        - name: Start nextcloud
          community.docker.docker_container:
            name: nextcloud
            image: nextcloud
            networks_cli_compatible: true
            networks:
              - name: nextcloud-net
                links:
                  - nextcloud-db
              # - name: api-net
              #   links:
              #     - webapp
              #     - kong
            ports:
              - '8081:80'
            volumes:
              - nextcloud:/var/www/html
            env:
              POSTGRES_HOST: nextcloud-db
              POSTGRES_DB: nextcloud
              POSTGRES_USER: nextcloud
              POSTGRES_PASSWORD: nextcloud
              NEXTCLOUD_ADMIN_PASSWORD: nextcloud
              NEXTCLOUD_ADMIN_USER: nextcloud
          register: nextcloud_register

        - name: nextcloud_register
          ansible.builtin.debug:
            var: nextcloud_register

        - name: Wait for nextcloud to accept connections
          ansible.builtin.wait_for:
            # host: "{{ nextcloud_register['container']\
            #   ['NetworkSettings']\
            #   ['Networks']\
            #   ['nextcloud-net']\
            #   ['IPAddress'] }}"
            host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
            port: 8081
            state: started
            connect_timeout: 1
            timeout: 30
          register: nextcloud_running
          until: nextcloud_running is success
          retries: 10
      when: not nextcloud_state.exists
